@Library('andes-library') _
pipeline {
  environment {
    registryCredential = "dockerhub"
  }
  agent {
    kubernetes {
      inheritFrom 'kube-agent'
      yaml '''
      spec:
        containers:
        - name: docker
          image: docker:19.03.1
          command:
            - sleep
          args:
            - 99d
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
        volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
'''
    }
  }
  stages {
    stage('Build API') {
      steps {
        container('docker') {
          script {
            test("Orly")
            def checkoutResponse = checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/hospitalneuquen/turnero-core.git']]])
            def BRANCH = GIT_BRANCH.replaceAll("origin/", "")
            def HASH = checkoutResponse.GIT_COMMIT
            docker.withRegistry('', registryCredential ) {
              def apiImage = docker.build("${API_IMAGE_NAME}:${BRANCH}-${HASH}", "./api")
              apiImage.push() 
              apiImage.push("${BRANCH}") 
              def appImage = docker.build("${APP_IMAGE_NAME}:${BRANCH}-${HASH}", "./app")
              appImage.push() 
              appImage.push("${BRANCH}") 
            }
          }
        }
      }
    }
  }
}

