pipeline {
  environment {
    registryCredential = "dockerhub"
  }
  agent {
    kubernetes {
      inheritFrom 'kube-agent'
      yaml '''
      spec:
        containers:
        - name: docker
          image: docker:19.03.1
          command:
            - sleep
          args:
            - 99d
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
        volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
'''
    }
  }
  stages {
    stage('Build API') {
      steps {
        container('docker') {
          script {
            def checkoutResponse = checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/hospitalneuquen/turnero-core.git']]])
            def BRANCH = GIT_BRANCH.replaceAll("origin/", "")
            def HASH = checkoutResponse.GIT_COMMIT
            print "-------------------------------------"
            print HASH
            print "-------------------------------------"
            print "docker build -f api/Dockerfile -t ${API_IMAGE_NAME}:${BRANCH}-${HASH} -t ${API_IMAGE_NAME}:${BRANCH} ./api"
            print "-------------------------------------"
            def apiImage = docker.build("${API_IMAGE_NAME}:${BRANCH}-${HASH}", "./api")
            apiImage.push() 
            def apiImage2 = docker.build("${API_IMAGE_NAME}:${BRANCH}", "./api")
            apiImage2.push() 
            def appImage = docker.build("${APP_IMAGE_NAME}:${BRANCH}-${HASH}", "./app")
            appImage.push() 
            def appImage2 = docker.build("${APP_IMAGE_NAME}:${BRANCH}", "./app")
            appImage2.push() 

          }
        }
      }
    }
  }
}

