@Library('andes-library') _
pipeline {
  environment {
    registryCredential = "dockerhub"
  }
  agent {
    kubernetes {
      inheritFrom 'kube-agent'
      yaml '''
      spec:
        containers:
        - name: docker
          image: docker:19.03.1
          command:
            - sleep
          args:
            - 99d
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
        volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
'''
    }
  }
  stages {
    stage('Build') {
      steps {
          script {
            node{
              echo "ANTES s------------------"
              echo IMAGE_NAME
              echo env.IMAGE_NAME
              echo "------------"
              # env.IMAGE_NAME required
              andesBuildDocker{
                repoUrl = "https://github.com/andes/api.git"
                branch = GIT_BRANCH
                pushToDockerRegistry = true
                registryCredential = "registryCredential"
              }
            }
          }
      }
    }
  }
}
