@Library('andes-library') _
pipeline {
  agent {
    kubernetes {
      inheritFrom 'kube-agent'
      yamlFile '../agent-kubernetes/dockerPod.yaml'
    }
  }
  stages {
    stage('Run Ansible') {
      steps {
          script {
            node{
              runAnsible{
                repo         = "https://github.com/andes-k8s/jenkins-pipelines.git"
                repo_branch  = "main"
                repo_folder = "clean-k8s-logs/"
                playbookFile = "playbook.yml"
                hostsFromParams = "HOSTS"
                userPrivateKeyFromParams = "ID_RSA"
              }
            }
          }
      }
    }
  }
}
