---
 - name: Free docker log space
   hosts: kubernetes
   become: true
   become_user: root
   tasks:
    - name: Clean now
      ansible.builtin.shell:
        cmd: "find /var/lib/docker/containers/*/*-json.log | xargs -i{} truncate -s 0 {}"
