@Library('andes-library') _
pipeline {
  environment {
    registryCredential = "dockerhub"
  }
  agent {
    kubernetes {
      inheritFrom 'kube-agent'
      yamlFile '../agent-kubernetes/dockerPod.yaml'
    }
  }
  stages {
    stage('Build API') {
      steps {
        script {
          node{
            andesBuildDocker{
              repoUrl = "https://github.com/hospitalneuquen/turnero-core.git"
              branch = GIT_BRANCH
              pushToDockerRegistry = true
              registryCredential = "dockerhub"
              dockerFileFolder = "./api"
              dockerImageName = "test"
            }
            andesBuildDocker{
              repoUrl = "https://github.com/hospitalneuquen/turnero-core.git"
              branch = GIT_BRANCH
              pushToDockerRegistry = true
              registryCredential = "dockerhub"
              dockerFileFolder = "./app"
              dockerImageName = APP_IMAGE_NAME
            }
          }
        }
      }
    }
  }
}

